FROM node:16.18.1-bullseye-slim

WORKDIR /app

RUN rm -rf node_modules
COPY ./package*.json ./
COPY env/.dev.env ./.env
RUN npm cache clean --force

COPY . .

RUN npm install --verbose

EXPOSE 4000
CMD npm run start:dev