# stage 1
FROM node:18-alpine as devModules
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm ci --only=development
COPY . .

# Stage 2
FROM node:18-alpine as productionBuild
WORKDIR /usr/src/app
COPY ./package*.json ./
COPY --from=devModules /usr/src/app ./
COPY . .
RUN npm run build
ENV NODE_ENV=production
RUN npm ci --only=production

# Stage 3
FROM node:18-alpine as production
WORKDIR /usr/src/app
COPY --from=productionBuild /usr/src/app/ ./

CMD npm run start:prod