name: Super-Linter

on: push

jobs:
  super-linter:
    name: Linting the code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          FILTER_REGEX_INCLUDE: .*src/.*
          TYPESCRIPT_ES_CONFIG_FILE: ../../.eslintrc.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}